version: '3'
services:
    p1-storefront:
        build: .
        container_name: p1-storefront
        ports:
            - "8025:80"
        networks: 
          - p1devnet
        restart: unless-stopped

networks:
  p1devnet:
    external: true