# Default values for p1-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enableCertIssuer: true
enableRedis: true

ingress:
  hostname: storefront.tst.protocol.one
  pathFrontend: 
   - /css
   - /img
   - /js
  pathBackend: 
   - /

certIssuer:
  email: admin@protocol.one

frontend:
  name: nginx
  role: frontend
  image: "p1hub/storefront.protocol.one-nginx"
  imageTag: latest
  port: 80
  replicas: 1
  service: 
    type: ClusterIP
    port: 80
    protocol: TCP
  configMap: 
    mountPath: /etc/nginx/conf.d/

backend:    
  name: nodejs
  role: backend
  image: "p1hub/storefront.protocol.one-nodejs"
  imageTag: latest
  port: 8080
  replicas: 1
  service: 
    type: ClusterIP
    port: 8080
    protocol: TCP
  env:
  - AUTH1_AUTHORIZE_URL
  - AUTH1_CLIENT_ID
  - AUTH1_CLIENT_SCOPE
  - AUTH1_CLIENT_SECRET
  - AUTH1_TOKEN_URL
  - AUTH1_REVOKE_TOKEN_URL
  - AUTH1_USERINFO_URL
  - PTAH_API_HOST_URL
  - MAILCHIMP_AUTHORIZE_URL
  - MAILCHIMP_CLIENT_ID
  - MAILCHIMP_CLIENT_SECRET
  - MAILCHIMP_TOKEN_URL
  - PUBLIC_HOST
  - REDIS_HOST
  - REDIS_PORT
  - ROUTES_PREFIX
  - SENTRY_DSN
  - SESSION_COOKIE_NAME
  - SESSION_COOKIE_SIGN_KEY
  - SERVER_PORT
  
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
